#:kivy 2.1.0

<SpacePrimaryButton>:
    pos_hint: {'center_y': 0.5, 'center_x': 0.5}
    icon: ''
    font_style: 'Button'
    size_hint_x: 1
    md_bg_color: app.theme_cls.primary_color
    text_color: app.theme_cls.text_color
    icon_color: app.theme_cls.text_color
    line_color: app.theme_cls.primary_color
    line_color_disabled: None
    md_bg_color_disabled: app.theme_cls.disabled_primary_color
